2020-04-23 15:57:56,101 ERROR: Exception on /ProfileUpdate/joseph [POST] [in /home/sartho/Coding/Project/GreenAnt/sys/lib/python3.5/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/home/sartho/Coding/Project/GreenAnt/sys/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    cursor, statement, parameters, context
  File "/home/sartho/Coding/Project/GreenAnt/sys/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 590, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: user.email

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/sartho/Coding/Project/GreenAnt/sys/lib/python3.5/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/sartho/Coding/Project/GreenAnt/sys/lib/python3.5/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/sartho/Coding/Project/GreenAnt/sys/lib/python3.5/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/sartho/Coding/Project/GreenAnt/sys/lib/python3.5/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/sartho/Coding/Project/GreenAnt/sys/lib/python3.5/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/sartho/Coding/Project/GreenAnt/sys/lib/python3.5/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/sartho/Coding/Project/GreenAnt/sys/lib/python3.5/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/sartho/Coding/Project/GreenAnt/Myna/routes.py", line 100, in ProfileUpdate
    db.session.commit()
  File "/home/sartho/Coding/Project/GreenAnt/sys/lib/python3.5/site-packages/sqlalchemy/orm/scoping.py", line 162, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/home/sartho/Coding/Project/GreenAnt/sys/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 1036, in commit
    self.transaction.commit()
  File "/home/sartho/Coding/Project/GreenAnt/sys/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 503, in commit
    self._prepare_impl()
  File "/home/sartho/Coding/Project/GreenAnt/sys/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 482, in _prepare_impl
    self.session.flush()
  File "/home/sartho/Coding/Project/GreenAnt/sys/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 2496, in flush
    self._flush(objects)
  File "/home/sartho/Coding/Project/GreenAnt/sys/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 2637, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/sartho/Coding/Project/GreenAnt/sys/lib/python3.5/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/home/sartho/Coding/Project/GreenAnt/sys/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/home/sartho/Coding/Project/GreenAnt/sys/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 2597, in _flush
    flush_context.execute()
  File "/home/sartho/Coding/Project/GreenAnt/sys/lib/python3.5/site-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
    rec.execute(self)
  File "/home/sartho/Coding/Project/GreenAnt/sys/lib/python3.5/site-packages/sqlalchemy/orm/unitofwork.py", line 589, in execute
    uow,
  File "/home/sartho/Coding/Project/GreenAnt/sys/lib/python3.5/site-packages/sqlalchemy/orm/persistence.py", line 236, in save_obj
    update,
  File "/home/sartho/Coding/Project/GreenAnt/sys/lib/python3.5/site-packages/sqlalchemy/orm/persistence.py", line 995, in _emit_update_statements
    statement, multiparams
  File "/home/sartho/Coding/Project/GreenAnt/sys/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 984, in execute
    return meth(self, multiparams, params)
  File "/home/sartho/Coding/Project/GreenAnt/sys/lib/python3.5/site-packages/sqlalchemy/sql/elements.py", line 293, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/sartho/Coding/Project/GreenAnt/sys/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1103, in _execute_clauseelement
    distilled_params,
  File "/home/sartho/Coding/Project/GreenAnt/sys/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1288, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/sartho/Coding/Project/GreenAnt/sys/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1482, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/sartho/Coding/Project/GreenAnt/sys/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/home/sartho/Coding/Project/GreenAnt/sys/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    cursor, statement, parameters, context
  File "/home/sartho/Coding/Project/GreenAnt/sys/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 590, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: user.email
[SQL: UPDATE user SET email=?, password_hash=?, avatar_img=? WHERE user.id = ?]
[parameters: ('sartho.joseph@gmail.com', 'pbkdf2:sha256:150000$gVBSOl3X$d5d22234c9fee42a1a93cdd371f21978b63e1fdfb0028a414dc666f6d1c86e72', 'http://127.0.0.1:5000/_uploads/photos/4_.jpg', 3)]
(Background on this error at: http://sqlalche.me/e/gkpj)
2020-04-23 19:52:23,456 INFO: Myna startup [in /home/sartho/Coding/Project/GreenAnt/Myna/__init__.py:55]
2020-04-23 19:53:57,059 INFO: Myna startup [in /home/sartho/Coding/Project/GreenAnt/Myna/__init__.py:55]
2020-04-23 19:54:18,779 INFO: Myna startup [in /home/sartho/Coding/Project/GreenAnt/Myna/__init__.py:55]
2020-04-23 20:18:57,488 INFO: Myna startup [in /home/sartho/Coding/Project/GreenAnt/Myna/__init__.py:55]
2020-04-23 20:23:17,069 INFO: Myna startup [in /home/sartho/Coding/Project/GreenAnt/Myna/__init__.py:55]
2020-04-23 20:24:17,723 INFO: Myna startup [in /home/sartho/Coding/Project/GreenAnt/Myna/__init__.py:55]
2020-04-23 20:24:59,840 INFO: Myna startup [in /home/sartho/Coding/Project/GreenAnt/Myna/__init__.py:55]
2020-04-23 20:26:19,241 INFO: Myna startup [in /home/sartho/Coding/Project/GreenAnt/Myna/__init__.py:55]
2020-04-23 20:31:11,445 INFO: Myna startup [in /home/sartho/Coding/Project/GreenAnt/Myna/__init__.py:55]
2020-04-23 20:33:00,375 INFO: Myna startup [in /home/sartho/Coding/Project/GreenAnt/Myna/__init__.py:55]
2020-04-23 20:35:44,500 INFO: Myna startup [in /home/sartho/Coding/Project/GreenAnt/Myna/__init__.py:55]
2020-04-23 20:36:31,961 INFO: Myna startup [in /home/sartho/Coding/Project/GreenAnt/Myna/__init__.py:55]
2020-04-24 12:43:37,462 INFO: Myna startup [in /home/sartho/Coding/Project/GreenAnt/Myna/__init__.py:55]
2020-04-24 12:43:54,815 ERROR: Exception on /Myna/Post [GET] [in /home/sartho/Coding/Project/GreenAnt/sys/lib/python3.5/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/home/sartho/Coding/Project/GreenAnt/sys/lib/python3.5/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/sartho/Coding/Project/GreenAnt/sys/lib/python3.5/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/sartho/Coding/Project/GreenAnt/sys/lib/python3.5/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/sartho/Coding/Project/GreenAnt/sys/lib/python3.5/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/sartho/Coding/Project/GreenAnt/sys/lib/python3.5/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/sartho/Coding/Project/GreenAnt/sys/lib/python3.5/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/sartho/Coding/Project/GreenAnt/sys/lib/python3.5/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/sartho/Coding/Project/GreenAnt/Myna/routes.py", line 36, in post
    form = PostForm()
NameError: name 'PostForm' is not defined
2020-04-24 12:44:22,572 INFO: Myna startup [in /home/sartho/Coding/Project/GreenAnt/Myna/__init__.py:55]
